### ISSUE TITLE
BUG: duplicate ATT/NO_ATT events synced to Action Network

### ISSUE THREAD

**Issue by Matt-Holland** [affinityworks/main#412]
## Symptoms

1. marking attendance for an event with N attendees creates 2N duplicate "replica" events in action network (where "replica" is defined as ATT/NO_ATT references to a "base" event)
2. seeding a database twice creates 2N replica events in action network (and prod DB), where N is the number of events that were in AN when the database was seeded (and thus synced down into the dev database)

## Acceptance Criteria

**Symptom 1:**

* **GIVEN:** i have created a new event in AN, synced it to AW and invited several members, 
  * **WHEN:** i mark the attendance of those members, sync back to AN, and login to AN, 
  * **THEN:** i should see only 3 events  corresponding to the event in question (the base event, and two replica ATT/NO_ATT events), and not one ATT or NO_ATT event for each attendee

**Symptom 2:**

* **GIVEN:** I have seeded a development database and created N base events and 2N replica events,
  * **WHEN:** I re-seed the database again from scratch
  * **THEN:** I should not observe 4N replica events in AN (or the prod db)

## Analysis

* We are confident that Symptom 2 is caused by an error in the class method `HasAttendanceEvent.create_and_sync_event`, which is called in an after-create hook any time any event is created (and thus would be called when events are created during a database seed, but *not* when marking attendance). This method fails to reference the identifier for the underlying base event (which would cause it to be deduped by the AN API), thus leading to the creation of dupe events.
  * see [this line](https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/app/models/concerns/has_attendance_event.rb#L13) for where `create_and_sync_event` creates an empty array of identifiers
  * see [this line](https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/app/models/api/action_network/event.rb#L5) for where `Api::ActionNetwork::Event#export!` parses an `event_id`, but then throws it away and does not reference it when hitting the API
*  We are not entirely sure how the above findings correlate to symptom 1. Notably, `Api:ActionNetwork::Attendance.export` **does** use the parsed `event_id` when hitting the API. So if it is the case that a failure to reference an underlying identifier is the reason why bugs are introduced in Symptom 1, it is unclear where that failure is introduced. More investigation required.
* It is also now unclear to me how Symtpom 1 is at all related to #459, which changes code that is only caused in after-create hooks. Also: if i closely observe the data dump, I don't see duplicates that take the form described in symptom 1. (Rather I see an exponential doubling in recursive replica creation.) Do we have any data we can inspect that looks like the failure mode described in symptom 1?

## Context

* inadequately fixed by #459 , which introduced a bug which clobbered events on Action Network, when syncing from AW
* related to #328

**Comment by aguestuser** [comment]
@rabble , @Matt-Holland : updated the ticket above with results of analysis performed yesterday. note that this might now be 2 tickets?

**Comment by aguestuser** [comment]
**Analysis of Attendance-Event duplication Bug:***

* **OBSERVATION**: the bug only happens when we create events. flow: import a base event -> always save (ie: `create`) that event in AW -> *always** create 2 attendance_event replicas of base event in AW and export them to AN, regardless of whether attendance_event replicas already exist in AN (and would be imported in a subsequent step during a DB seed) this because `after_create` hook always on any event always calls `create_remote_event`, which in turn calls `sync_and_create` once for each kind of attendance event replica. see [create_remote_event here](https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/app/models/concerns/has_remote_event.rb#L10) and [create_and_sync here](https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/app/models/concerns/has_attendance_event.rb#L8)
* **BUT**: we want to be able to infer if the replica events already exist, and thus not create and export them if they do. further, we want to not have to wait until the entire import (of every event in AN) has run in order to do this. (in a naive solution, we could wait until the import has run, iterate over every newly imported event, check for whether it has associated `attendance_events` in our DB and only create associated `attendance_event`s if it doesn't. this seems really grosss. let's do better!) to wit...
* **QUESTION**: given only a base event, how may we determine whether it already has replica attendance_events in ActionNetwork?
  * **ASSUMPTION 1**: this information is *somehow* available from inspecting the model. most likely it might be available on the `identifiers` field as `att_identifier:some-uuid`. if so, we extract that identifier and include it in our post. if AN API acts as we hope it would, it would respond to a create request for an attendance_event that already exists by not creating anything.
    * **KEY QUESTION:** is the `att_identifier` available upon inspecting a newly created `event`? see [this fixture](https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/test/fixtures/files/attendances/original_attendance.json#L4) for the identifier we'd like to grab, and hope exists on the JSON response for importing our base event.
    * **GUESS**: if we *can* grab the `att_identifier` field from a newly imported event, would not overwriting identifiers with an empty array [here](https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/app/models/concerns/has_attendance_event.rb#L13) solve the problem?
  * **ASSUMPTION 2**: this data is *not* available from inspecting the model and we don't mind making network calls. -> we'd have to make a network call to find out if there were any attendance events associated with the original event or not.
  * **ASSUMPTION 3**: this data is *not* available from inspecting the model and we don't want to make network calls. -> make 2 different methods for creating events: `#create_from_import` and `create`. only the latter includes the create hook that

**Related Questions:**

* will trying to export an attendance_event with a foreign identifier that already existed effectively prevent it from being created as a dupe? I *think* this is true, and I can test it in the HAL browser, but it would be quicker if someone who already knows could tell me.
* where in the execution flow are foreign identifiers created? (I cannot tell from inspecting the code. Action Network identifiers are UUIDs and clearly get created by Action Network. `advocacycommons` identifiers tend to be sequential integers from all the sample data i can observer. but `att_identifier`s that i can observe are uuids, and appear to be nowhere created in our code, suggesting that Action Network creates them.  But if action network creates `att_identifier` identifiers, why does it give them this special identifier prefix? How does it know to use `att` since that's our own construction?  In any case, I'd like to know where they come from and when in the execution flow they are available to me, since understanding that is central to squashing this bug. GUESS: they are only ever created by AN and we consume them from JSON and them write them to DB when importing. is that right? how could i confirm this by inspecting our code?

**Comment by aguestuser** [comment]
(other related question: why are there no tests for exporting events? there are lots of tests for importing them. am i looking in the worng place? its the first place i went to try to get my footing on this problem and was sad to find nothing.)

**Comment by aguestuser** [comment]
ps @Matt-Holland as per our discussion just now, here's another breadcrumb. the tests for the `event_attandance` model, which includes the `att_identifier` field referenced above:

https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/test/models/attendance_event_test.rb#L22-L23

**Comment by aguestuser** [comment]
curious, where those came from, i grep'ed (searched) for the uuids in question and found them in these fixtures:

https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/test/fixtures/files/attendances/original_attendance.json#L2-L6

**Comment by aguestuser** [comment]
^-- that being the response to a post request to the `events/:id/attendances` endpoint of this form in the test:

https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/test/models/attendance_event_test.rb#L32

**Comment by aguestuser** [comment]
so the question(s) are:

* where did that UUID come from?
* could we ever make a GET request and retrieve an event with an `att_identifier` already stored on it? because if so, my **GUESS** above will work!
* but i don't know the answer to either of those questions! (paging @rabble , who i think might be available soon! :))

**Comment by aguestuser** [comment]
bad news update.

**first:** it is *not* possible to glean any information about whether any given newly created event already has replica `attendance_event`s in ActionNetwork, simply by inspecting the model (my hope in *ASSUMPTION 1* above), as evidenced by this pry session in which I tried to find it:

![attendance-event-debug-no-identfiers-on-model](https://user-images.githubusercontent.com/6032844/35239997-12f31a08-ff80-11e7-864b-ec94a6ec3340.png)

^-- note the `identifiers` field, which has the value `["action_network:727a51d4-a736-4d0d-acec-6c87faa2b045", "advocacycommons:1"]`

**second:** it is also *not* possible to infer the connection between any given base event and any given attendance_event that replicates it by making network calls, thus **ASSUMPTION 2** above also does not hold. as evidence, see:

* the results of [this GET request](https://actionnetwork.org/api/browser/#https://actionnetwork.org/api/v2/events/727a51d4-a736-4d0d-acec-6c87faa2b045) to the ActionNetwork API for the event inspected in the pry session above. (retrieved from the ActionNetwork HAL browser using its 'action_network` identifer). note that there is no data available about any event other than the base event itself. 
* the results of [this GET request](https://actionnetwork.org/api/browser/#https://actionnetwork.org/api/v2/events/0d1b1c43-226d-42b2-ba98-dc2fe87d273b) for a randomly selected `attendance_event` created from a recent database seed. note that there is no data available about any base event from which the `attendance_event` was replicatd
* we may further confirm our conclusion that the API never reveals data about attendance events in GET requests for base events (or vice versa) by inspecting the full set of events here: https://actionnetwork.org/api/browser/#https://actionnetwork.org/api/v2/events/

**thus:** it looks like we're out of options and must proceed under **ASSUMPTION 3** above, and make 2 separate methods for creating an event: `#create` and `#create_from_import` (which, if we can get the logic right, might be the cleanest solution after all.)

**Comment by aguestuser** [comment]
welp. playing **ASSUMPTION 3** doesn't really work out either, because that gambit of that assumption is to try to avoid replicating events when importing. but this doesn't work because we *might* sometimes want to replicate an event on import, but other times not. the problem reduces to the fact that we don't know merely by the fact that we are importing an event whether it already has `attendance_event` replicas on ActionNetwork, and (as far as i can tell) it is impossible to know this.  (FWIW, if it was possible to solve the problem by distinguishing between `#create` and `#create_from_import` [this](https://github.com/affinityworks/main/blob/b68ed37f03c77fbc5da6d214c0af607d3b6be775/app/models/api/action_network/import.rb#L93) is the seam where we would insert such a distinction.)

to illustrate the logic of the arugment above: imagine we have imported and replicated 10 events on monday morning. when we seed the database for a review app on monday afternoon, we don't want to replicate these events again when we import them to seed the databse. but then, first thing on tuesday, someone creates a new, 11th, event on ActionNetwork, and we go to import this event as part of our regular syncing. we *do* want to replicate this, because we haven't seen it before.

because we may only inspect one event at a time, there is no way to tell, merely by inspecting an event, whether or not we should or should not replicate it. so it seems like our earlier decision to always create replica `attendance_events` to have on hand has us somewhat in a bind.

if there is some sort of way to make a network call to find out whether a base event has replicas (which hours inspecting the ActionNetwork API have not revealed to me), then we can solve the problem without backtracking on that decision. otherwise we might have to. and that feels YUUUUUCKY as heck!

perhaps someone can remind me why we thought it was necessary to always immediately create these replicas? perhaps the problem it was trying to work around (querying ActionNetwork) might hold some sort of clue for a way to get the information i'm missing but looking for in the `after_create` hook above?

**Comment by aguestuser** [comment]
**new acceptance criteria for bugfix:**

1. issue GET request to https://actionnetwork.org/api/v2/events/, count number of total events
2. run `./bin/seed-db`
3. issue GET request to https://actionnetwork.org/api/v2/events/, number of total events should be same as in step 1.* 

(*it is okay if it is one more, provided the only additional event is the `only a test_ATT` event identified by @Matt-Holland today)

**Comment by aguestuser** [comment]
**new plan for bugfix:**

* whenever we create replica events from a base event, give the replica events a foreign identifier that is derrived in a deterministic, repeatable manner from the action-network identifier of the base event. (eg: take the action network identifier and append either `att` or `no_att` to it
* always export newly-created replica events and rely on the action network API to not duplicate events when it sees a repeated foreign identifier
